/**
 * 10-20 Standard Electrode Placement and Anatomical Montage Registry
 */

export interface ElectrodeChannelDetail {
  leadName: string;
  friendlyName: string;
  placement: string;
  whatItMeasures: string;
  waveMeaning: string;
  clinicalPurpose: string;
  anatomicalRegion: string;
  dominantRhythm: string;
  typicalAmp: string;
}

export type LeadPlainDetail = ElectrodeChannelDetail;

export interface ElectrodePosition {
  x: number;
  y: number;
  label: string;
  region: string;
}

export const ELECTRODE_MONTAGE_REGISTRY: Record<string, ElectrodeChannelDetail> = {
  "Fp1": {
    leadName: "Fp1",
    friendlyName: "Fp1 — Left Frontopolar EEG",
    anatomicalRegion: "Left Prefrontal Pole (Brodmann Area 10)",
    placement: "Standard 10-20 position situated on the lower left forehead, directly superior to the left supraorbital ridge.",
    whatItMeasures: "Prefrontal cortical potentials, vertical electro-oculographic (EOG) dipole transitions, and frontopolar baseline activity.",
    waveMeaning: "Rapid low-voltage desynchronization during focused mental processing; high-amplitude slow monophasic deflections during eye blinks.",
    clinicalPurpose: "Serves as anterior reference for Frontal Alpha Asymmetry (FAA) indexing and vertical blink artifact screening.",
    dominantRhythm: "Beta (13–30 Hz) / Ocular transient",
    typicalAmp: "15–40 µV"
  },
  "Fp2": {
    leadName: "Fp2",
    friendlyName: "Fp2 — Right Frontopolar EEG",
    anatomicalRegion: "Right Prefrontal Pole (Brodmann Area 10)",
    placement: "Standard 10-20 position situated on the lower right forehead, directly superior to the right supraorbital ridge.",
    whatItMeasures: "Right prefrontal cortical potential, ocular dipole field, and anterior hemispheric balance.",
    waveMeaning: "Bilateral comparison with Fp1 reveals relative hemispheric arousal and anterior valence shifts.",
    clinicalPurpose: "Used in frontopolar differential analysis and electro-oculographic artifact gating.",
    dominantRhythm: "Beta (13–30 Hz) / Low Gamma",
    typicalAmp: "15–40 µV"
  },
  "F3": {
    leadName: "F3",
    friendlyName: "F3 — Left Frontal EEG",
    anatomicalRegion: "Left Dorsolateral Prefrontal Cortex (DLPFC, BA 9/46)",
    placement: "Standard 10-20 electrode positioned over the left superior frontal gyrus, midway between Fp1 and C3.",
    whatItMeasures: "Left frontal cortical activation, working memory load, mental calculation, and approach motivation.",
    waveMeaning: "Pronounced Beta power (18–28 Hz) elevation reflects active cognitive workload; alpha power suppression reflects localized cortical engagement.",
    clinicalPurpose: "Primary lead for evaluating task-induced cognitive workload, arithmetic stress, and frontal alpha asymmetry.",
    dominantRhythm: "Beta (18–28 Hz)",
    typicalAmp: "10–30 µV"
  },
  "F4": {
    leadName: "F4",
    friendlyName: "F4 — Right Frontal EEG",
    anatomicalRegion: "Right Dorsolateral Prefrontal Cortex (DLPFC, BA 9/46)",
    placement: "Standard 10-20 electrode positioned over the right superior frontal gyrus, midway between Fp2 and C4.",
    whatItMeasures: "Right frontal cortical activation, vigilance, autonomic arousal, and withdrawal motivation.",
    waveMeaning: "Selective suppression of right-frontal Alpha rhythms (8–12 Hz) relative to F3 signifies heightened sympathetic arousal.",
    clinicalPurpose: "Paired with F3 to calculate the validated Frontal Alpha Asymmetry metric ln(F4 Alpha) - ln(F3 Alpha).",
    dominantRhythm: "Alpha (8–12 Hz) / Beta",
    typicalAmp: "10–32 µV"
  },
  "Fz": {
    leadName: "Fz",
    friendlyName: "Fz — Frontal Midline EEG",
    anatomicalRegion: "Medial Prefrontal & Anterior Cingulate Circuit (ACC)",
    placement: "Standard 10-20 position situated along the sagittal midline at 30% distance from nasion toward inion.",
    whatItMeasures: "Frontal Midline Theta (FmTheta, 4–8 Hz) oscillations generated by medial prefrontal and anterior cingulate networks.",
    waveMeaning: "Synchronized sinusoidal theta bursts emerge during sustained attention, Stroop conflict monitoring, and error processing.",
    clinicalPurpose: "Gold-standard electrophysiological marker for executive control recruitment and cognitive interference workload.",
    dominantRhythm: "Frontal Midline Theta (4–8 Hz)",
    typicalAmp: "20–50 µV"
  },
  "Cz": {
    leadName: "Cz",
    friendlyName: "Cz — Central Midline (Vertex) EEG",
    anatomicalRegion: "Sensorimotor Cortex / Central Vertex (BA 4/3)",
    placement: "Exact midpoint on top of the neurocranium, intersection of sagittal midline and coronal interaural line.",
    whatItMeasures: "Sensorimotor rhythms, Mu oscillations (8–13 Hz), and central vertex somatic evoked potentials.",
    waveMeaning: "Mu rhythm desynchronization occurs during motor readiness, physical movement, or somatic tension.",
    clinicalPurpose: "Acts as central physiological ground/reference and index of somatic arousal and motor quieting.",
    dominantRhythm: "Mu / Beta (12–20 Hz)",
    typicalAmp: "15–45 µV"
  },
  "Pz": {
    leadName: "Pz",
    friendlyName: "Pz — Parietal Midline EEG",
    anatomicalRegion: "Superior Parietal Lobule & Precuneus (BA 7)",
    placement: "Sagittal midline position located at 70% distance from nasion toward inion, posterior to vertex.",
    whatItMeasures: "Parietal associative integration, spatial attention orienting, and P300 cognitive event-related potentials.",
    waveMeaning: "Synchronized alpha and beta power shifts denote spatial working memory allocation and sensory gating.",
    clinicalPurpose: "Evaluates parietal resting-state alpha coherence and cognitive stimulus processing capacity.",
    dominantRhythm: "Alpha (8–13 Hz) / P300",
    typicalAmp: "20–55 µV"
  },
  "O1": {
    leadName: "O1",
    friendlyName: "O1 — Left Occipital EEG",
    anatomicalRegion: "Left Primary Visual Cortex (Brodmann Area 17/18)",
    placement: "Standard 10-20 position over the left posterior occipital pole, superior to the inion.",
    whatItMeasures: "Classical posterior Berger Alpha rhythm (8.0–12.0 Hz) reflecting sensory visual cortex idling.",
    waveMeaning: "High-amplitude rhythmic sinusoidal waves appear during eyes-closed resting baseline; attenuate immediately upon visual stimulus.",
    clinicalPurpose: "Gold-standard electrophysiological verification of resting baseline relaxation and neural synchrony.",
    dominantRhythm: "Posterior Alpha (9–11 Hz)",
    typicalAmp: "30–70 µV"
  },
  "O2": {
    leadName: "O2",
    friendlyName: "O2 — Right Occipital EEG",
    anatomicalRegion: "Right Primary Visual Cortex (Brodmann Area 17/18)",
    placement: "Standard 10-20 position over the right posterior occipital pole, superior to the inion.",
    whatItMeasures: "Right hemisphere posterior visual alpha rhythms and inter-hemispheric sensory symmetry.",
    waveMeaning: "Smooth synchronized alpha rhythms during eyes-closed quiet wakefulness; identical frequency tuning to O1.",
    clinicalPurpose: "Verifies bilateral posterior alpha symmetry and rules out unilateral sensory focal suppression.",
    dominantRhythm: "Posterior Alpha (9–11 Hz)",
    typicalAmp: "30–70 µV"
  },
  "Fpz-Cz": {
    leadName: "Fpz-Cz",
    friendlyName: "Fpz-Cz — Frontopolar-Central Bipolar Derivation",
    anatomicalRegion: "Anteroposterior Longitudinal Montaged Axis",
    placement: "Bipolar montage bridging lower midline forehead (Fpz) to exact vertex (Cz).",
    whatItMeasures: "Deep restorative slow-wave oscillations (Delta 0.5–4 Hz) and frontal-central sleep micro-architecture.",
    waveMeaning: "High-voltage slow waves signify synchronized slow-wave sleep (N3); rapid desynchronized activity indicates wakefulness.",
    clinicalPurpose: "Standard clinical polysomnography sleep staging derivation.",
    dominantRhythm: "Delta (0.5–4 Hz) / Sleep Spindles",
    typicalAmp: "25–100 µV"
  },
  "Pz-Oz": {
    leadName: "Pz-Oz",
    friendlyName: "Pz-Oz — Parieto-Occipital Bipolar Derivation",
    anatomicalRegion: "Posterior Sensory-Visual Axis",
    placement: "Bipolar montage bridging parietal midline (Pz) to occipital base (Oz).",
    whatItMeasures: "Sleep spindles (11–16 Hz), K-complexes, and posterior alpha background.",
    waveMeaning: "Rhythmic bursts reflect healthy Stage N2 sleep; smooth baseline waves reflect relaxed eyes-closed wakefulness.",
    clinicalPurpose: "Specialist PSG derivation for sleep architecture and micro-arousal monitoring.",
    dominantRhythm: "Alpha (8–12 Hz) / Spindles (12–14 Hz)",
    typicalAmp: "20–60 µV"
  }
};

export const ELECTRODE_POSITIONS: Record<string, ElectrodePosition> = {
  "Fp1": { x: 36, y: 22, label: "Fp1", region: "Left Frontopolar" },
  "Fp2": { x: 64, y: 22, label: "Fp2", region: "Right Frontopolar" },
  "F3": { x: 30, y: 38, label: "F3", region: "Left Frontal (DLPFC)" },
  "Fz": { x: 50, y: 36, label: "Fz", region: "Frontal Midline" },
  "F4": { x: 70, y: 38, label: "F4", region: "Right Frontal" },
  "Cz": { x: 50, y: 52, label: "Cz", region: "Central Vertex" },
  "Pz": { x: 50, y: 68, label: "Pz", region: "Parietal Midline" },
  "O1": { x: 36, y: 82, label: "O1", region: "Left Occipital" },
  "O2": { x: 64, y: 82, label: "O2", region: "Right Occipital" },
  "Fpz-Cz": { x: 50, y: 30, label: "Fpz-Cz", region: "Frontopolar-Central" },
  "Pz-Oz": { x: 50, y: 76, label: "Pz-Oz", region: "Parieto-Occipital" }
};

export const PLAIN_ENGLISH_LEADS = ELECTRODE_MONTAGE_REGISTRY;

